Convert FormInput to TextField
Grocee/grocee-ui pull request #28
Opened 2018-09-15 17:19 UTC by indirap

I branched this off of my other PR, so the changes might look a bit weird, but once that's merged, it should be all good to go.

2018-09-15 17:25 UTC, indirap commented on src/Grocery/AddList.js
> -			headerRight: (
It's not straightforward to get this button working because you don't have access to the component's state in static functions like this. It looks like you we don't have a delete list feature either in Inventory, so I'm going to remove this for now, and figure out a better way to do this.

2018-09-16 04:01 UTC, vatthikorn requested changes
Not sure why but whenever I hit add new inventory button, it gives me an error.

2018-09-16 04:01 UTC, vatthikorn commented on src/Grocery/Grocery.js
> +						returnKeyType='next'
This should be `done`

2018-09-16 15:13 UTC, zackva commented on src/Grocery/Grocery.js
> +						returnKeyType='next'
Has this been addressed?

2018-09-16 16:23 UTC, indirap commented on src/Grocery/Grocery.js
> +						returnKeyType='next'
Sorry, forgot that one. Just fixed it!

2018-09-16 16:30 UTC, vatthikorn approved these changes

2018-09-16 16:30 UTC, merged